[theme]
base="light"
primaryColor="#1abc9c"
backgroundColor="#f9f9f9"

[theme.sectionStyle]
backgroundColor="#ffffff"

[theme.h1Style]
backgroundColor="#e74c3c"

[theme.h2Style]
backgroundColor="#3498db"

[theme.h3Style]
backgroundColor="#9b59b6"

[theme.h4Style]
backgroundColor="#2ecc71"

[theme.h5Style]
backgroundColor="#f1c40f"

[theme.h6Style]
backgroundColor="#e67e22"

[theme.pStyle]
backgroundColor="#bdc3c7"
