[theme]
base="light"
primaryColor="#d33682"
backgroundColor="#1797b5"
secondaryBackgroundColor="#586e75"
textColor="#f7f2e1"

# primaryColor="#d33682"
# backgroundColor="#10b4dc"
# secondaryBackgroundColor="#586e75"
# textColor="#f7f2e1"



# [theme]
# primaryColor="#d33682"
# backgroundColor="#002b36"
# secondaryBackgroundColor="#586e75"
# textColor="#fafafa"
# font="sans serif"



# base="light"
# backgroundColor="#69ffca"
# secondaryBackgroundColor="#e4eaae"
# textColor="#901543"


